#! /bin/sh
xrandr --output HDMI-1 --mode 1360x768
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a lxappearance state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a zathura state=titling
bspc rule -a Kupfer.py focus=on

nitrogen --restore
compton &
xrandr --dpi 90 
polybar -c "~/.config/polybar/config" -r example &
#xmobar -d &
#~/.config/bspwm/bspwmbar

